---
# tasks file for ansible-role-docker

- name: Include linux distribution specific variables
  include_vars:
    dir: vars
    files_matching: "{{ item }}.yml"
    ignore_unknown_extensions: yes
  loop:
    - "{{ ansible_pkg_mgr }}"
    - "{{ ansible_lsb.id }}"
    - "{{ ansible_lsb.id }}-{{ ansible_lsb.major_release }}"
    - "{{ ansible_lsb.id }}-{{ ansible_lsb.release }}"

- block:
    - name: Remove older versions of Docker
      package:
        name: "{{ docker_older_versions | default([]) }}"
        state: absent

    - name: Install Docker dependencies
      package:
        name: "{{ docker_dependencies | default([]) }}"
        state: present

    - name: Include package manager specific tasks
      include_tasks: "{{ ansible_pkg_mgr }}.yml"

    - name: Install Docker
      package:
        name: "{{ docker_package_name }}"
        state: "{{ 'latest' if docker_version == 'latest' else 'present' }}"

    - name: Create Docker group
      group:
        name: "{{ docker_group }}"
        state: present
        system: yes

    - name: Add users to Docker group
      user:
        append: yes
        groups: "{{ docker_group }}"
        name: "{{ item }}"
        state: present
      with_items: "{{ docker_group_members | default([]) }}"

    - name: Start Docker daemon
      service:
        enabled: yes
        name: docker
        state: started
  become: yes
  become_user: "{{ become_user }}"

- name: Run docker-compose tasks
  include_tasks: docker_compose.yml
  when: docker_compose_install
...
