---
- block:
    - name: install prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - "linux-image-extra-{{ ansible_kernel }}"
        - linux-image-extra-virtual
    - name: add GPG key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        state: present
        id: 58118E89F3A912897C070ADBF76221572C52609D
    - name: add docker repo
      apt_repository:
        filename: docker
        repo: "{{ docker_apt_repo }}"
        state: present
        update_cache: yes
  become: yes